### PR TITLE
Add collapse functionality for elements in the tree

### PR DESCRIPTION
**Pull request by dobladov**
Fixes: #27

### CODE REVIEW

**Comment by dobladov** [comment]
tree

**Comment by dr0i** [comment]
Don't know what I am doing wrong: collapse/expand nowt working, nor in ff or chromium.  https://test.skohub.io/literarymachine/skos/w3id.org/class/hochschulfaecher/scheme.html however is fine.

**Comment by dobladov** [comment]
> Don't know what I am doing wrong: collapse/expand nowt working, nor in ff or chromium. https://test.skohub.io/literarymachine/skos/w3id.org/class/hochschulfaecher/scheme.html however is fine.

Do you have any errors in the console @dr0i ? It seems to work for me on both FF and Chromium.

**Comment by dr0i** [comment]
Also, the links seems to be not realtive but absolute e.g. they are going to file:///w3id.org/class/hochschulfaecher/F56.html. As you see I am browsing the files. Ah - this may be the problem, yes? I just have to expose them via the server:8080, yes? Boy!

**Comment by dr0i** [comment]
Uh, yes that's it!

**Pull request merged**
